export enum FirebaseHelpRequestState {
  REQUESTED = 'REQUESTED',
  ACCEPTED = 'ACCEPTED',
  CANCELED = 'CANCELED',
  DONE = 'DONE',
  FAILED = 'FAILED',
  DELETED = 'DELETED',
  RESIGNED = 'RESIGNED',
}
